export const SET_SUBMIT_SHELTER_DIALOG_OPEN = 'SET_SUBMIT_SHELTER_DIALOG_OPEN';
export const SET_SUBMIT_EMERGENCY_DIALOG_OPEN = 'SET_SUBMIT_EMERGENCY_DIALOG_OPEN';
export const SET_SELECTED_TAB = 'SET_SELECTED_TAB';

